const Themes = {
  'Default' : {
    icon: '#666',
    iconSelected: '#ffbc00',
    background: 'white',
    blindClosed: '#5d5d5d',
    blindOpen: '#303F9F',
    blindTextOff: 'white',
    blindTextOn: '#FBC02D',
    buttonMixed: '#4a4a4a',
    buttonOff: '#8a8a8a',
    buttonOn: '#ffbc00',
    menuButton: '#666',
    text: '#666',
    textMixed: 'white',
    textOff: 'white',
    textOn: '#3E2723'
  },
  'Lighter' : {
    icon: '#666',
    iconSelected: '#ffbc00',
    background: 'white',
    blindClosed: '#a9a9a9',
    blindOpen: '#718bbb',
    blindTextOff: '#5d5b5b',
    blindTextOn: '#FBC02D',
    buttonMixed: '#808080',
    buttonOff: '#eee',
    buttonOn: '#ffbc00',
    menuButton: '#666',
    text: '#808080',
    textMixed: '#808080',
    textOff: '#808080',
    textOn: 'white'
  },
  'Light Blue' : {
    icon: '#666',
    iconSelected: '#3366FF',
    background: '#99CCFF',
    blindClosed: '#5d5d5d',
    blindOpen: '#303F9F',
    blindTextOff: 'white',
    blindTextOn: '#FBC02D',
    buttonMixed: '#4a4a4a',
    buttonOff: '#8a8a8a',
    buttonOn: '#3366FF',
    menuButton: '#666',
    text: 'black',
    textMixed: 'white',
    textOff: 'white',
    textOn: 'white'
  },
  'Light Green' : {
    icon: '#666',
    iconSelected: '#009900',
    background: '#66FF99',
    blindClosed: '#5d5d5d',
    blindOpen: '#303F9F',
    blindTextOff: 'white',
    blindTextOn: '#FBC02D',
    buttonMixed: '#4a4a4a',
    buttonOff: '#8a8a8a',
    buttonOn: '#009900',
    menuButton: '#666',
    text: 'black',
    textMixed: 'white',
    textOff: 'white',
    textOn: 'white'
  }
}
export default Themes
